
//Java Comments
/*
In computer programming,
        comments are a portion of the program that are completely ignored by Java compilers.
        They are mainly used to help programmers to understand the code.

 */

/*
One thing to keep in mind is that comments should never be used to replace a means to explain badly written code in English.
        Always write well-structured and self-explanatory code.
        Then, utilize comments.


 */

/*
In Java, every application begins with a class definition.
        In the program, Main is the name of the class
A class is a non-primitive or user-defined data type in Java

every Java application has a class definition,
and the name of the class should match the filename in Java.
 */
public class Main {

   /*

   a collection of statements that perform some specific task and return the result to the caller

   the main function is the entry point of your Java application,
    and it's mandatory in a Java program.

    */

    public static void main(String[] args) {
        //Java System.out.println() is used to print an argument that is passed to it
        System.out.println("Hello world!");
    }
}
